# Intro to Pandas
___

**pandas** provides data structures and data manipulation tools designed for fast & easy data cleaning and analysis.

pandas adopts array-based computing from NumPy, but is designed for **tabular** or **heterogenous** data.

pandas has two primary data structures:

- **Series** - one-dimensional array-like object with a sequence of values having the same datatype
- **DataFrame** - rectangular table of data with ordered collection of columns, each of which can be a different value type

In [1]:
#As allways we import pandas and numpy
import pandas as pd
import numpy as np

### Series

Has a sequence of values (all the same datatype) and an associated array of data labels called its **index**. If not specified otherwise, the index values are sequential integers.

pandas can automatically determine datatype of values when a Series is created, but datatype can also be specified.

A Series is like a fixed-length, ordered dict with a mapping of index values to data values.

The array representation and index object of a Series can be accessed via its **values** and **index** attributes.

Problem 1: Create a series 4 numerical values. Print the series, the values and the index of the series.

In [4]:
x = pd.Series([6,7,8,9])
x

0    6
1    7
2    8
3    9
dtype: int64

Problem 2: Create a new series with the same values but with string values for the index. Select and print out one of the values in the series with the index.

In [6]:
x = pd.Series([6,7,8,9], index = ["a","d","b","c"])
x[["d"]]

d    7
dtype: int64

Problem 3: You can also create a series from a python dict. Create a dict called `states_dict` with the state name as the key and the number as the value.
'Ohio' 35000
'Texas' 71000
'Oregon' 16000 
'Utah' 5000
Use the dict `states_dict` to create a series called `states_series`.

In [21]:
states_dict = {"Ohio":35000, "Texas":71000, "Oregon":16000, "Utah":5000}

states_series = pd.Series(states_dict)
states_series

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Problem 4: Updated the index of `state_series` to be the abbreviation of the state names. Do this in place.

In [22]:
states_series.index = ["OH", "TX", "OR", "UT"]

states_series

OH    35000
TX    71000
OR    16000
UT     5000
dtype: int64

### DataFrame

A pandas DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type.

Sort of a dict of Series all sharing the same index.

- DataFrames have both row and column indices
- DataFrames are physically 2D, but can represent higher-dimensional data using hierarchical indexing
- DataFrame rows are sometimes referred to as axis=0
- DataFrame columns are sometimes referred to as axis=1


You can create DataFrames from dicts as well.

In [3]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
      }

df = pd.DataFrame(data)
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Problem 5: Update the index of the DataFrame df to be the words for each number. i.e. 1 -> one

In [19]:
df.index = ["zero", "one", "two", "three", "four", "five"]
df

        state  year  pop
zero     Ohio  2000  1.5
one      Ohio  2001  1.7
two      Ohio  2002  3.6
three  Nevada  2001  2.4
four   Nevada  2002  2.9
five   Nevada  2003  3.2

Problem 6: Figure out two ways to access a column from df. Output the results.

In [23]:
print(df["state"], "\n")
print(df.state)

zero       Ohio
one        Ohio
two        Ohio
three    Nevada
four     Nevada
five     Nevada
Name: state, dtype: object

zero       Ohio
one        Ohio
two        Ohio
three    Nevada
four     Nevada
five     Nevada
Name: state, dtype: object

Problem 7: Figure out two ways to access a row from df. Output the results.

In [25]:
print(df.loc["zero"], "\n")
print(df.iloc[0])

state    Ohio
year     2000
pop       1.5
Name: zero, dtype: object

state    Ohio
year     2000
pop       1.5
Name: zero, dtype: object

Problem 8: Add a new column to your dataframe called 'rating' with the values `[5,4,3,2,1,0]`

In [31]:
df["rating"] = [5,4,3,2,1,0]
df

        state  year  pop  rating
zero     Ohio  2000  1.5       5
one      Ohio  2001  1.7       4
two      Ohio  2002  3.6       3
three  Nevada  2001  2.4       2
four   Nevada  2002  2.9       1
five   Nevada  2003  3.2       0

Problem 9: Create another column called `nonsense` that is the rating multiplied by the pop.

In [35]:
df["nonsense"] = df["rating"] * df["pop"]
df

        state  year  pop  rating  nonsense
zero     Ohio  2000  1.5       5       7.5
one      Ohio  2001  1.7       4       6.8
two      Ohio  2002  3.6       3      10.8
three  Nevada  2001  2.4       2       4.8
four   Nevada  2002  2.9       1       2.9
five   Nevada  2003  3.2       0       0.0

Problem 10: Create three series using using numpy.

* series_numerical: The values 0-4 with index a-e
* series_zeros: All zeros with index a-e
* series_random: 5 random numbers qith index a-e

DataFrame called `numeric_df` from these three series. Each series will be a row and the columns will be a-e.

In [70]:
idx = pd.Index(list("abcde"))
series_numerical = pd.Series(np.arange(5), index = idx)
series_zeros = pd.Series(np.zeros(5), index = idx)
series_random = pd.Series(np.random.rand(5), index = idx)

series_list = list([series_numerical, series_zeros, series_random])
series_index = pd.Index(["series_numerical", "series_zeros", "series_random"])
numeric_df = pd.DataFrame(series_list, index = series_index)

numeric_df

# I did consult chatgpt on this concerning the style I wrote with declaring the few extra variables (idx, series_list, series_index) and 
# potential other ways to write it

                         a         b         c         d         e
series_numerical  0.000000  1.000000  2.000000  3.000000  4.000000
series_zeros      0.000000  0.000000  0.000000  0.000000  0.000000
series_random     0.738231  0.901329  0.169578  0.801932  0.646176

Problem 11: Transpose the DataFrame `numeric_df` so that the series become columns instead of rows. Save this to a variable called `transposed_numeric_df`. Rename the columns to `numerical`, `zeros`, and `random`.

In [71]:
transposed_numeric_df = numeric_df.T 
transposed_numeric_df.columns = ["numerical", "zeros", "random"]
transposed_numeric_df

   numerical  zeros    random
a        0.0    0.0  0.738231
b        1.0    0.0  0.901329
c        2.0    0.0  0.169578
d        3.0    0.0  0.801932
e        4.0    0.0  0.646176

Problem 12: Output `transposed_numeric_df` ordered by `random` descending.

In [72]:
transposed_numeric_df_random_descending = transposed_numeric_df.sort_values("random", ascending = False)
transposed_numeric_df_random_descending

   numerical  zeros    random
b        1.0    0.0  0.901329
d        3.0    0.0  0.801932
a        0.0    0.0  0.738231
e        4.0    0.0  0.646176
c        2.0    0.0  0.169578

Problem 13: Select all rows from `transposed_numeric_df` where the column `numerical` is greater than 2.

In [80]:
greater_than_2 = transposed_numeric_df.loc[transposed_numeric_df.numerical > 2]
greater_than_2

   numerical  zeros    random
d        3.0    0.0  0.801932
e        4.0    0.0  0.646176

Problem 14: Add a column called `random_5` that is the column random multiplied by 5. Select all rows from `transposed_numeric_df` where `numerical` is greater than `random_5`.

In [91]:
transposed_numeric_df["random5"] = transposed_numeric_df["random"] * 5
greater_than_random_5 = transposed_numeric_df["numerical"] > transposed_numeric_df["random5"]
greater_than_random_5

a    False
b    False
c     True
d    False
e     True
dtype: bool

Problem 15: Add a column to transposed_numberic_df called `even` that is True when `numerical` is even and `False` when `numerical` is odd.

In [90]:
def is_even(x):
    if x["numerical"] % 2 == 0:
        return True
    else:
        False

transposed_numeric_df["even"] =  transposed_numeric_df.apply(transposed_numeric_df["numerical"])
transposed_numeric_df

KeyError: "Column(s) ['a', 'b', 'c', 'd', 'e'] do not exist"

Problem 16: Add a column called `even_odd` that has the value `odd` when `numerical` is odd and `even` when `numerical` is even.

Problem 17: Print out the sum of all columns.

Problem 18: Print out index of the row with the max value for each column. i.e. for `numerical` it will be the last row `e` because it has a value of 5.