# Week 8 Overview

This week will be a mix of data joining/merging problems and linear algebra. 
The first 5 problems are data cleaning and the final 4 problems are linear algebra.

There are multiple ways to combine data. These methods are common cross multiple languages like pandas, SQL, and R. At times the naming is different but the general concepts apply. 

### **Joining or Merging**
This is a process of combining two datasets by adding the columns of one dataset to the other by some logical relationship between the columns. 

In SQL we call this joining but pandas has two functions:

**merge** - The default behavor for merge is to combine on columns matching.

**join** - The default behavor for join is to combine on the column index matching. 

Often times I will colloquially use the word "join" for either merging or joining in pandas. 

Left Dataset
| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |

Right Dataset
| key    | different_value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

Data Joined on key

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | cat |
| A2 | $80     | dog |
| A3    | $420    | apple |

Typically we refer to the starting dataset as the left dataset and the one being added as the right. 

The logic is typically that there is the same value in a specific column in both datasets. SQL allows for slightly more advanced logic which we will learn next quarter. Today we will focus on just columns matching. 

There are different types of joins that you will explore in this notebook (inner, outer, left, right, cross). The typical visual that is used to illustration these concepts in Ven Diagrams. If you are getting stuck trying to pick the right join type search for "types of joins" and look at the pictures that come up.


## **Concat or Union**

This is a process of combining two dataset by adding the rows of one dataset to the end of another. There is no logic required for this. This is called conact in pandas and union in SQL. 

In most version of SQL you are required to have the same columns in both datasets. In pandas you don't have to. If I concatenate the two dataset above in pandas I would get:

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | null |
| A2 | $80     | null |
| A3    | $420    | null |
| A1  | null    | cat |
| A2 | null     | dog |
| A3    | null    | apple |

However if my right dataset looked like this:

| key    | value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

then I could union them in SQL or concat in pandas to get:

| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_1 = pd.DataFrame({"ints": range(100)})
df_2 = pd.DataFrame({"ints": range(-10, 10)}, index=range(-10, 10))


df_1['threes'] = np.floor(df_1['ints']/3) * 3

df_2['evens'] = df_2['ints']*2
df_2['threes'] = np.floor(df_2['ints']/3) * 3

print("df_1: ")
print(df_1,"\n\n")
print("df_2: ")
print(df_2)

df_1:
    ints  threes
0      0     0.0
1      1     0.0
2      2     0.0
3      3     3.0
4      4     3.0
..   ...     ...
95    95    93.0
96    96    96.0
97    97    96.0
98    98    96.0
99    99    99.0

[100 rows x 2 columns]


df_2:
     ints  evens  threes
-10   -10    -20   -12.0
-9     -9    -18    -9.0
-8     -8    -16    -9.0
-7     -7    -14    -9.0
-6     -6    -12    -6.0
-5     -5    -10    -6.0
-4     -4     -8    -6.0
-3     -3     -6    -3.0
-2     -2     -4    -3.0
-1     -1     -2    -3.0
0       0      0     0.0
1       1      2     0.0
2       2      4     0.0
3       3      6     3.0
4       4      8     3.0
5       5     10     3.0
6       6     12     6.0
7       7     14     6.0
8       8     16     6.0
9       9     18     9.0

### Problem 1:

Your first task will be to create a dataset by `merging` `df_1` and `df_2` on the `ints` column where the match on both sides. The results will be a dataframe with 10 rows and 5 columns.

You will then create the same dataframe by using the `join` function and joining the two datasets where the indexes are equal. There will be a little more work of handle column duplication so look up the error and figure out arguments to set. How many columns do you get in this case?

In [4]:
df_3 = pd.merge(df_1, df_2, on="ints")
df_3

   ints  threes_x  evens  threes_y
0     0       0.0      0       0.0
1     1       0.0      2       0.0
2     2       0.0      4       0.0
3     3       3.0      6       3.0
4     4       3.0      8       3.0
5     5       3.0     10       3.0
6     6       6.0     12       6.0
7     7       6.0     14       6.0
8     8       6.0     16       6.0
9     9       9.0     18       9.0

In [5]:
df_4 = df_1.join(df_2, on="ints", how="inner", lsuffix="_left", rsuffix="_right")

df_4

   ints  ints_left  threes_left  ints_right  evens  threes_right
0     0          0          0.0           0      0           0.0
1     1          1          0.0           1      2           0.0
2     2          2          0.0           2      4           0.0
3     3          3          3.0           3      6           3.0
4     4          4          3.0           4      8           3.0
5     5          5          3.0           5     10           3.0
6     6          6          6.0           6     12           6.0
7     7          7          6.0           7     14           6.0
8     8          8          6.0           8     16           6.0
9     9          9          9.0           9     18           9.0

## Problem 2:

Next you will perform the same merge as above three times with the following modifications:

* You want to keep all rows in `df_1` even if there is no match found in `df_2`
* You want to keep all rows in `df_2` even if there is no match found in `df_1`
* You want to keep all rows in `df_1` and `df_2` even if there is no match found in the other dataframe


How many rows do you end up with in each case? 

Think through a scenario where you might want to do this and add it as a comment above each merge.

In [6]:
df_5 = pd.merge(df_1, df_2, on="ints", how="left")
df_5

    ints  threes_x  evens  threes_y
0      0       0.0    0.0       0.0
1      1       0.0    2.0       0.0
2      2       0.0    4.0       0.0
3      3       3.0    6.0       3.0
4      4       3.0    8.0       3.0
..   ...       ...    ...       ...
95    95      93.0    NaN       NaN
96    96      96.0    NaN       NaN
97    97      96.0    NaN       NaN
98    98      96.0    NaN       NaN
99    99      99.0    NaN       NaN

[100 rows x 4 columns]

In [7]:
df_6 = pd.merge(df_1, df_2, on="ints", how="right")
df_6

    ints  threes_x  evens  threes_y
0    -10       NaN    -20     -12.0
1     -9       NaN    -18      -9.0
2     -8       NaN    -16      -9.0
3     -7       NaN    -14      -9.0
4     -6       NaN    -12      -6.0
5     -5       NaN    -10      -6.0
6     -4       NaN     -8      -6.0
7     -3       NaN     -6      -3.0
8     -2       NaN     -4      -3.0
9     -1       NaN     -2      -3.0
10     0       0.0      0       0.0
11     1       0.0      2       0.0
12     2       0.0      4       0.0
13     3       3.0      6       3.0
14     4       3.0      8       3.0
15     5       3.0     10       3.0
16     6       6.0     12       6.0
17     7       6.0     14       6.0
18     8       6.0     16       6.0
19     9       9.0     18       9.0

In [8]:
df_7 = pd.merge(df_1, df_2, on="ints", how="outer")
df_7

     ints  threes_x  evens  threes_y
0     -10       NaN  -20.0     -12.0
1      -9       NaN  -18.0      -9.0
2      -8       NaN  -16.0      -9.0
3      -7       NaN  -14.0      -9.0
4      -6       NaN  -12.0      -6.0
..    ...       ...    ...       ...
105    95      93.0    NaN       NaN
106    96      96.0    NaN       NaN
107    97      96.0    NaN       NaN
108    98      96.0    NaN       NaN
109    99      99.0    NaN       NaN

[110 rows x 4 columns]

### Problem 3

Now we are going to merge on columns that are not the same. Merge on the following:

* Merge `df_1` and `df_2` where `df_1.ints = df_2.evens`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, keep all rows from `df_1` even if there is no match found in `df_2`
* Merge `df_1` and `df_2` where `df_1.threes = df_2.threes`, only keep rows where there is a value for either dataframe


How many rows do you end up with in each case? Are there any duplications? (try: value_count)

Think through a scenario where you might want to do this and add it as a comment above each merge.

In [9]:
df_8 = pd.merge(df_1, df_2, left_on="ints", right_on="evens", how="outer")
df_8

     ints_x  threes_x  ints_y  evens  threes_y
0       NaN       NaN   -10.0  -20.0     -12.0
1       NaN       NaN    -9.0  -18.0      -9.0
2       NaN       NaN    -8.0  -16.0      -9.0
3       NaN       NaN    -7.0  -14.0      -9.0
4       NaN       NaN    -6.0  -12.0      -6.0
..      ...       ...     ...    ...       ...
105    95.0      93.0     NaN    NaN       NaN
106    96.0      96.0     NaN    NaN       NaN
107    97.0      96.0     NaN    NaN       NaN
108    98.0      96.0     NaN    NaN       NaN
109    99.0      99.0     NaN    NaN       NaN

[110 rows x 5 columns]

In [10]:
df_9 = pd.merge(df_1, df_2, left_on="ints", right_on="threes", how="outer")
df_9

     ints_x  threes_x  ints_y  evens  threes_y
0       NaN       NaN   -10.0  -20.0     -12.0
1       NaN       NaN    -9.0  -18.0      -9.0
2       NaN       NaN    -8.0  -16.0      -9.0
3       NaN       NaN    -7.0  -14.0      -9.0
4       NaN       NaN    -6.0  -12.0      -6.0
..      ...       ...     ...    ...       ...
111    95.0      93.0     NaN    NaN       NaN
112    96.0      96.0     NaN    NaN       NaN
113    97.0      96.0     NaN    NaN       NaN
114    98.0      96.0     NaN    NaN       NaN
115    99.0      99.0     NaN    NaN       NaN

[116 rows x 5 columns]

In [11]:
df_10 = pd.merge(df_1, df_2, left_on="ints", right_on="threes", how="left")
df_10

     ints_x  threes_x  ints_y  evens  threes_y
0         0       0.0     0.0    0.0       0.0
1         0       0.0     1.0    2.0       0.0
2         0       0.0     2.0    4.0       0.0
3         1       0.0     NaN    NaN       NaN
4         2       0.0     NaN    NaN       NaN
..      ...       ...     ...    ...       ...
101      95      93.0     NaN    NaN       NaN
102      96      96.0     NaN    NaN       NaN
103      97      96.0     NaN    NaN       NaN
104      98      96.0     NaN    NaN       NaN
105      99      99.0     NaN    NaN       NaN

[106 rows x 5 columns]

In [12]:
df_11 = pd.merge(df_1, df_2, left_on="threes", right_on="threes", how="outer")
df_11

     ints_x  threes  ints_y  evens
0       NaN   -12.0   -10.0  -20.0
1       NaN    -9.0    -9.0  -18.0
2       NaN    -9.0    -8.0  -16.0
3       NaN    -9.0    -7.0  -14.0
4       NaN    -6.0    -6.0  -12.0
..      ...     ...     ...    ...
123    95.0    93.0     NaN    NaN
124    96.0    96.0     NaN    NaN
125    97.0    96.0     NaN    NaN
126    98.0    96.0     NaN    NaN
127    99.0    99.0     NaN    NaN

[128 rows x 4 columns]

### Problem 4

Add a new the column to `df_2` called `threes_string` that is the `threes` column converted to a string. Attempt to merge `df_1` and `df_2` where `df_1.threes = df_2.threes_string` with an inner join. What happens? Why?

In [13]:
""" 
You cannot merge these two dataframes on df_1.threes and df_2.threes_string as they are 
incompatible data types. 
""";

df_2["threes_string"] = df_2["threes"].astype(str)
# df_12 = pd.merge(df_1,df_2, left_on="threes", right_on="threes_string", how="inner")
# df_12

### Problem 5

Now you will play around with `pd.concat` by doing the following:

* Concatenate `df_1` and `df_2` keeping all rows, columns and indexes
* Concatenate `df_1` and `df_2` keeping all rows and columns but ignore the indexes from the orginal dataframes and instead have the index on this dataframe be zero to the number of rows.
* Concatenate `df_1` and `df_2` keeping all rows and indexes the same but only keeping columns that exist in both dataframes

In [14]:
df_concat = pd.concat([df_1, df_2], ignore_index=False)
print(df_concat)
print("------------------------------------------------")

    ints  threes  evens threes_string
0      0     0.0    NaN           NaN
1      1     0.0    NaN           NaN
2      2     0.0    NaN           NaN
3      3     3.0    NaN           NaN
4      4     3.0    NaN           NaN
..   ...     ...    ...           ...
5      5     3.0   10.0           3.0
6      6     6.0   12.0           6.0
7      7     6.0   14.0           6.0
8      8     6.0   16.0           6.0
9      9     9.0   18.0           9.0

[120 rows x 4 columns]
------------------------------------------------

## Linear Algebra: Rank and Column Space

### Problem 6
You will now learn how to create random matrices with arbitrary rank (subject to the constraints about matrix sizes, etc.). To create an $m \times n$ matrix with rank $r$, multiply a random $m \times r$ matrix with a random $r \times n$ matrix. Implement this in Python and confirm that the rank is indeed $r$. 

What happens if you set $r > min{M,N}$, and why does that happen?

In [15]:
matrix_1 = np.arange(12).reshape((3,4))
matrix_1_rank = np.linalg.matrix_rank(matrix_1)

matrix_3 = np.arange(8).reshape(4,matrix_1_rank)
matrix_4 = np.arange(8).reshape(matrix_1_rank,4)

matrix_5 = matrix_3 @ matrix_4
matrix_5_rank = np.linalg.matrix_rank(matrix_5)

try:
    if matrix_1_rank == matrix_5_rank:
        print("The matrix ranks are equal")
except: 
    print("The matrix ranks are NOT equal.")

The matrix ranks are equal

### Problem 7
Interestingly, the matrices $A$, $A^T$, $A^T A$, and $AA^T$ all have the same rank. Write code to demonstrate this, using random matrices of various sizes, shapes (square, tall, wide), and ranks. Create a total of 6 random, two of each size that have different sizes and ranks.

In [33]:
matrix_6 = np.random.randint(1,20,(7,2))
matrix_7 = np.random.randint(1,20,(3,7))
matrix_8 = np.random.randint(1,20,(3,4))
matrix_9 = np.random.randint(1,20,(4,5))
matrix_10 = np.random.randint(1,20,(5,3))
matrix_11 = np.random.randint(1,20,(3,6))

def same_rank(arr: np.array) -> bool:
    assert np.linalg.matrix_rank(arr) == np.linalg.matrix_rank(arr.T)
    assert np.linalg.matrix_rank(arr) == np.linalg.matrix_rank(arr.T @ arr)
    assert np.linalg.matrix_rank(arr) == np.linalg.matrix_rank((arr @ arr.T))
    return True

def all_ranks_are_equal() -> None:
    assert same_rank(matrix_6) == True
    assert same_rank(matrix_7) == True
    assert same_rank(matrix_8) == True
    assert same_rank(matrix_9) == True
    assert same_rank(matrix_10) == True
    assert same_rank(matrix_11) == True
    print("Each matrix has the same rank as its transpose. Marix multipliation of A @ A.T and A.T @ A " \
    "all have the same rank as the orignial matrix.")

all_ranks_are_equal()

Each matrix has the same rank as its transpose. Marix multipliation of A @ A.T and A.T @ A all have the same rank as the orignial matrix.

### Problem 8

Demonstrate the addition rule of matrix rank $(r(A + B) ≤ r(A) + r(B))$ by creating three pairs of rank-1 matrices that have a sum with 
1. rank-0
2. rank-1
3. rank-2

Then repeat this exercise using matrix multiplication instead of addition.

### Problem 9

The goal of this exercise is to answer the question is $v \in C(A)$?

Create a rank-3 matrix $A \in \mathbb{R}^{4 \times 3}$ and vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. 

Follow the algorithm described in the [In the Column Space?](https://learning.oreilly.com/library/view/practical-linear-algebra/9781098120603/ch06.html#id335) section of Practical Linear Algebra to determine whether the vector is in the column space of the matrix. 

Rerun the code multiple times to see whether you find a consistent pattern. 

Next, use a $A \in \mathbb{R}^{4 \times 4}$ rank-4 matrix and a vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. What happens in this case? Why?